(function(){var l=Handlebars.template;(Handlebars.discovery=Handlebars.discovery||{}).templates=l(function(g,h,e,k,a){function b(a,b,x){var c="",f;c+='\n        <section id="';(f=e.id)?f=f.call(a,{hash:{},data:b}):(f=a.id,f=typeof f===q?f.apply(a):f);c+=o(f)+'" class="';(f=e.className)?f=f.call(a,{hash:{},data:b}):(f=a.className,f=typeof f===q?f.apply(a):f);c+=o(f)+'">\n            <header class="discovery-col-header">\n\n                ';if((f=e["if"].call(a,b.index===b.length-1,{hash:{},inverse:j.noop,
fn:j.program(3,d,b),data:b}))||f===0)c+=f;c+="\n\n                ";if((f=e["if"].call(a,a.type==="organic",{hash:{},inverse:j.noop,fn:j.programWithDepth(i,b,x),data:b}))||f===0)c+=f;c+="\n                ";if((f=e["if"].call(a,a.type==="promoted",{hash:{},inverse:j.noop,fn:j.program(7,v,b),data:b}))||f===0)c+=f;c+='\n\n            </header>\n            <ul class="discovery-posts">\n            </ul>\n        </section>\n    ';return c}function d(a,d){var f="";f+='\n                    \n                    <div class="discovery-options">\n                        <span class="publisher-anchor-color"><a href="#" class="discovery-help" data-action="discovery-help">'+
o(e.t.call(a,gettext("What's this?"),{hash:{},data:d}))+"</a></span>\n                    </div>\n                ";return f}function i(a,d,f){var c="";c+="\n                    <h2>"+o(e.t.call(a,gettext("Also on %(forumName)s"),{hash:{forumName:{partial:"forumName",context:f.forum,executePartial:!0}},data:d}))+"</h2>\n                ";return c}function v(a,d){var f="";f+="\n                    <h2>"+o(e.t.call(a,gettext("Around The Web"),{hash:{},data:d}))+"</h2>\n                ";return f}function f(a,
d,f){var c="",b,i;c+='\n        <li class="discovery-post" id="discovery-link-';if((b=e["if"].call(a,a.id,{hash:{},inverse:j.program(19,s,d),fn:j.program(17,m,d),data:d}))||b===0)c+=b;c+='">\n            <header class="discovery-post-header">\n                <h3 title="';(b=e.title)?b=b.call(a,{hash:{},data:d}):(b=a.title,b=typeof b===q?b.apply(a):b);c+=o(b)+'">\n                    <a ';if((b=j.invokePartial(k.linkAttributes,"linkAttributes",a,e,k,d))||b===0)c+=b;c+=' data-role="discovery-thread-title" class="title publisher-anchor-color line-truncate" data-line-truncate="2">\n                        '+
o(e.html.call(a,a.title,{hash:{},data:d}))+"\n                    </a>\n\n                    ";if((i=e["if"].call(a,(b=f.variant,b==null||b===!1?b:b.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(21,l,d),data:d}))||i===0)c+=i;c+="\n\n                </h3>\n\n                ";if((i=e.unless.call(a,(b=f.variant,b==null||b===!1?b:b.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(29,t,d),data:d}))||i===0)c+=i;c+="\n\n            </header>\n\n            ";if((i=e["if"].call(a,(b=f.variant,b==null||
b===!1?b:b.contentPreviews)&&a.preview,{hash:{},inverse:j.noop,fn:j.program(34,y,d),data:d}))||i===0)c+=i;c+="\n\n        </li>\n    ";return c}function m(a,d){var b="",c;b+="o";(c=e.id)?c=c.call(a,{hash:{},data:d}):(c=a.id,c=typeof c===q?c.apply(a):c);b+=o(c);return b}function s(a,d){var b="",c;b+="p";(c=e.body_id)?c=c.call(a,{hash:{},data:d}):(c=a.body_id,c=typeof c===q?c.apply(a):c);b+=o(c);return b}function l(a,d){var b="",c;b+="\n                        ";if((c=e["if"].call(a,a.posts>0,{hash:{},
inverse:j.program(24,n,d),fn:j.program(22,z,d),data:d}))||c===0)b+=c;b+="\n                        ";if((c=e["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(27,r,d),data:d}))||c===0)b+=c;b+="\n                    ";return b}function z(a,d){var b="",c;b+='\n                            <span class="inline-meta">\n                                ';if((c=j.invokePartial(k.discoveryPostCount,"discoveryPostCount",a,e,k,d))||c===0)b+=c;b+="\n                            </span>\n                        ";
return b}function n(a,d){var b="",c;b+="\n                            ";if((c=e["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(25,u,d),data:d}))||c===0)b+=c;b+="\n                        ";return b}function u(a,d){var b="",c;b+='\n                                <span class="inline-meta">';(c=e.createdAgo)?c=c.call(a,{hash:{},data:d}):(c=a.createdAgo,c=typeof c===q?c.apply(a):c);b+=o(c)+"</span>\n                            ";return b}function r(a,d){var b="",c;b+='\n                            <span class="inline-meta">\n                                ';
(c=e.brand)?c=c.call(a,{hash:{},data:d}):(c=a.brand,c=typeof c===q?c.apply(a):c);b+=o(c)+"\n                            </span>\n                        ";return b}function t(a,d){var b="",c;b+='\n                    <ul class="meta">\n                        ';if((c=e["if"].call(a,a.posts>0,{hash:{},inverse:j.noop,fn:j.program(30,w,d),data:d}))||c===0)b+=c;b+="\n                        ";if((c=e["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(32,A,d),data:d}))||c===0)b+=c;b+="\n                    </ul>\n                ";
return b}function w(a,d){var b="",c;b+='\n                            <li class="comments">\n                                ';if((c=j.invokePartial(k.discoveryPostCount,"discoveryPostCount",a,e,k,d))||c===0)b+=c;b+="\n                            </li>\n                        ";return b}function A(a,d){var b="",c;b+='\n                            <li class="time">';(c=e.createdAgo)?c=c.call(a,{hash:{},data:d}):(c=a.createdAgo,c=typeof c===q?c.apply(a):c);b+=o(c)+"</li>\n                        ";
return b}function y(a,b){var d="",c;d+="\n                ";if((c=j.invokePartial(k.discoveryContentPreview,"discoveryContentPreview",a,e,k,b))||c===0)d+=c;d+="\n            ";return d}function B(){return'target="_blank" rel="nofollow"'}function C(a,d){var b="";b+="\n        "+o(e.t.call(a,gettext("1 comment"),{hash:{},data:d}))+"\n    ";return b}function D(a,d){var b="";b+="\n        "+o(e.t.call(a,gettext("%(numPosts)s comments"),{hash:{numPosts:a.posts},data:d}))+"\n    ";return b}this.compilerInfo=
[2,">= 1.0.0-rc.3"];var e=e||g.helpers,k=k||g.partials,a=a||{},g="",p,o=this.escapeExpression,q="function",j=this;if((p=e.partial.call(h,"discoveryMain",{hash:{},inverse:j.noop,fn:j.programWithDepth(function(a,d,f){var c="",i;c+='\n<div id="';(i=e.id)?i=i.call(a,{hash:{},data:d}):(i=a.id,i=typeof i===q?i.apply(a):i);c+=o(i)+'" class="discovery-main">\n    <div id="discovery-note" style="display:none;">\n        <div class="alert">\n        <a href="#" class="close" data-action="discovery-help-close" title="'+
o(e.t.call(a,gettext("Close this box"),{hash:{},data:d}))+'">\u00d7</a>\n        '+o(e.t.call(a,gettext("Disqus helps you find new and interesting content, discussions and products. Some sponsors and ecommerce sites may pay us for these recommendations and links. %(learnMore)s or %(feedback)s."),{hash:{learnMore:{partial:"learnMore",context:f,executePartial:!0},feedback:{partial:"feedback",context:f,executePartial:!0}},data:d}))+"\n        </div>\n    </div>\n\n    ";if((i=e.each.call(a,a.sections,
{hash:{},inverse:j.noop,fn:j.programWithDepth(b,d,a),data:d}))||i===0)c+=i;c+="\n\n</div>\n";return c},a,h),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,"learnMore",{hash:{},inverse:j.noop,fn:j.program(9,function(a,d){var b="";b+='\n    <a href="http://help.disqus.com/customer/portal/articles/666278-introducing-promoted-discovery-and-f-a-q-"\n        target="_blank">'+o(e.t.call(a,gettext("Learn more"),{hash:{},data:d}))+"</a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,
"feedback",{hash:{},inverse:j.noop,fn:j.program(11,function(a,d){var b="";b+='\n    <a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">\n        '+o(e.t.call(a,gettext("give us feedback"),{hash:{},data:d}))+"</a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,"forumName",{hash:{},inverse:j.noop,fn:j.program(13,function(a,d){var b="",c;b+="\n    <strong>";(c=e.name)?c=c.call(a,{hash:{},data:d}):(c=a.name,c=typeof c===q?c.apply(a):c);b+=o(c)+"</strong>\n";return b},
a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,"discoveryCollection",{hash:{},inverse:j.noop,fn:j.program(15,function(a,d){var b="",c;b+="\n    ";if((c=e.each.call(a,a.collection,{hash:{},inverse:j.noop,fn:j.programWithDepth(f,d,a),data:d}))||c===0)b+=c;b+="\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,"linkAttributes",{hash:{},inverse:j.noop,fn:j.program(36,function(a,d){var b="",c;b+='\n    href="';(c=e.redirectUrl)?c=c.call(a,{hash:{},data:d}):(c=a.redirectUrl,
c=typeof c===q?c.apply(a):c);b+=o(c)+'" ';if((c=e["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(37,B,d),data:d}))||c===0)b+=c;b+="\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,"discoveryContentPreview",{hash:{},inverse:j.noop,fn:j.program(39,function(a,b){var F;var E;var x;var d="",c;d+="\n    <a ";if((c=j.invokePartial(k.linkAttributes,"linkAttributes",a,e,k,b))||c===0)d+=c;d+=' class="top-comment" data-role="discovery-top-comment">\n        <img src="'+o((E=
(x=(c=(c=a.preview,c==null||c===!1?c:c.author),c==null||c===!1?c:c.avatar),c=x,c==null||c===!1?c:c.cache),c=E,typeof c===q?c.apply(a):c))+'" alt="'+o(e.t.call(a,gettext("Avatar"),{hash:{},data:b}))+'" data-role="discovery-avatar">\n        <p><span class="user" data-role="discovery-top-comment-author">'+o((F=(c=(c=a.preview,c==null||c===!1?c:c.author),c==null||c===!1?c:c.name),c=F,typeof c===q?c.apply(a):c))+'</span> &#8212; <span data-role="discovery-top-comment-snippet" class="line-truncate" data-line-truncate="3">'+
o((c=(c=a.preview,c==null||c===!1?c:c.plaintext),typeof c===q?c.apply(a):c))+"</span></p>\n    </a>\n";return d},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(h,"discoveryPostCount",{hash:{},inverse:j.noop,fn:j.program(41,function(a,d){var b="",c;b+="\n    ";if((c=e["if"].call(a,a.posts===1,{hash:{},inverse:j.program(44,D,d),fn:j.program(42,C,d),data:d}))||c===0)b+=c;b+="\n";return b},a),data:a}))||p===0)g+=p;g+="\n";return g})})();
DISQUS.define("discovery.collections",function(){var l={},g=DISQUS.testing,h=DISQUS.JSON,e=_.strip,k=DISQUS.use("discovery.helpers"),a=DISQUS.use("discovery.models"),b=Backbone.Collection.extend({url:function(a){return DISQUS.api.getURL(a)},fetch:function(a){a=a||{};a.reset=!0;return Backbone.Collection.prototype.fetch.call(this,a)},parse:function(a){return a.response}});l.PostCollection=function(a){var b=a.prototype;return a.extend({url:function(){return b.url.call(this,"discovery/listTopPost.json")},
parse:function(a){for(var a=b.parse.call(this,a),d=0,i=a.length;d<i;d++)a[d].plaintext=e(a[d].message);return a}})}(b);var d=function(d){var b=d.prototype;return d.extend({initialize:function(d,b){this.model=a[this.modelName];this.sourceThread=b.sourceThread;this.modelAttributes=b.modelAttributes;this.getBanditJSON=_.memoize(this.getBanditJSON)},fetch:function(a){a=a||{};a.data=a.data||{};a.data.thread=this.sourceThread.id;return b.fetch.call(this,a)},parse:function(a){a=b.parse.call(this,a);if("bandit"in
a)this.bandit=a.bandit,a=a.results;if(!_.isArray(a))return[];for(var d=0,i=a.length;d<i;d++)_.extend(a[d],this.modelAttributes);return a},getBanditJSON:function(){return h.stringify(this.bandit)}})}(b);l.RelatedThreadCollection=function(a){var d=a.prototype;return a.extend({modelName:"RelatedThread",url:function(){return d.url.call(this,"discovery/listRelated.json")},parse:function(a){return this.rejectInvalid(d.parse.call(this,a))},rejectInvalid:function(a){var d=[],b,i=this.sourceThread;if(DISQUS.debug)return a.slice();
for(var e=0,v=a.length;e<v;e++)b=a[e],b.id==i.id||b.link==i.link?this.reportInvalid(b,"Link or id of related thread points back to thread on this page (circular reference)"):b.title.search(/^https?:\/\//)===0?this.reportInvalid(b,"Title looks like a url (begins with http:// or https://)"):d.push(b);return d},reportInvalid:function(a,d){var b=k.log;b("An organic link failed validation:",a.title,a.link,"(id =",a.id+")");b("Reason:",d)}})}(d);l.AdvertisementCollection=function(a){var d=a.prototype;return a.extend({modelName:"Advertisement",
url:function(){return d.url.call(this,"discovery/listPromoted.json")}})}(d);if(g)l.BaseCollection=b,l.BaseContentCollection=d;return l});
DISQUS.define("discovery.helpers",function(l,g){var h={},e=!1,k=!1;h.config=function(a){e=!!a.lineTruncationEnabled;k=!!a.consoleLoggingEnabled};h.isMobile=function(){return DISQUS.browser.mobile};var a=function(){};l.console&&(a=function(){if(k){var a=_.toArray(arguments);a.unshift("[Discovery]");l.console.log.apply?l.console.log.apply(l.console,a):l.console.log(a.join(" "))}});h.log=a;h.allowLog=function(a){if(a===g)return k;k=!!a};h.allowLineTruncate=function(a){if(a===g)return e;e=!!a};h.lineTruncate=
function(a,d){function i(){return s.scrollHeight-s.offsetHeight>0.2*k}function v(){m.lastChild&&!_.contains(["...","\u2026"],m.lastChild.nodeValue)&&(n=m.appendChild(l.document.createTextNode(" "+h)),i()&&(m.removeChild(n),m.removeChild(m.lastChild),v()))}if(e){var f=DISQUS.logError||function(){};if(!a.closest("body").length)return void f("lineTruncate called on el not on DOM");if(a.text().length<1)return void f("lineTruncated called on empty el");if(_.any(a.children(),function(a){return a.nodeType!==
3}))return void f("lineTruncate called on non-flat el");var m=a[0],s=m;if(a.css("display")!=="block")for(;s.parentNode;)if(s=s.parentNode,$(s).css("display")==="block")break;var k=parseFloat(a.css("font-size"),10);if(i()){var d=d||{},f=d.lines||1,h=d.ellipsis,n,g=a.text();if(g.length){var r=a.width()/k,f=parseInt(r*f,10),g=g.split(/\s/),r=0;a.empty();for(var t=0,w=g.length;t<w;t++){r+=g[t].length+1;if(r>=f)break;m.appendChild(document.createTextNode(" "+g[t]))}if(i()){do n=m.removeChild(m.lastChild);
while(i())}else{do n=m.appendChild(document.createTextNode(" "+g[t++]));while(!i()&&t<w);m.removeChild(n)}h&&(_.isString(h)||(h="\u2026"),v())}}}};h.balancedPartition=function(a){var d=_.keys(a),i=Math.floor(_.reduce(a,function(a,d){return a+d},0)/2),e=d.length+1;i+=1;var f=Array(e),m,g;for(m=0;m<e;m++)f[m]=Array(i),f[m][0]={};for(g=1;g<i;g++)f[0][g]=!1;var h,k,n,l={};for(g=1;g<i;g++)for(m=1;m<e;m++){h=d[m-1];k=a[h];n=_.clone(f[m-1][g]);if(!n&&k<=g&&(n=_.clone(f[m-1][g-k])))n[h]=k,l=n;f[m][g]=n}return[l,
_.omit(a,_.keys(l))]};return h});
DISQUS.define("discovery.models",function(){var l={},g=DISQUS.ISO_8601,h=function(e){var g=e.prototype;return e.extend({defaults:{redirectUrl:null,signedUrl:null,userId:null,sourceThreadId:null,forumId:null,forum:null,majorVersion:null,variant:null,isExperiment:!1},redirectPayload:function(){var a={url:this.get("signedUrl"),imp:DISQUS.juggler.impId,forum_id:this.get("forumId"),forum:this.get("forum"),thread_id:this.get("sourceThreadId"),major_version:this.get("majorVersion")};if(this.get("isExperiment"))a.variant=
this.get("variant");if(this.has("userId"))a.user_id=this.get("userId");if(this.collection&&this.collection.bandit)a.bandit=this.collection.getBanditJSON();return a},redirectUrl:function(){var a=this.get("redirectUrl"),b=this.redirectPayload();return DISQUS.serialize(a,b)},toJSON:function(){var a=g.toJSON.call(this);a.redirectUrl=this.redirectUrl();return a},toString:function(){return this.get("title")+" "+this.get("link")+" (id = "+this.id+")"}})}(Backbone.Model);l.RelatedThread=function(e){var h=
e.prototype;return e.extend({defaults:_.defaults({createdAgo:!1},h.defaults),initialize:function(){if(this.get("createdAgo")){var a;a=this.get("createdAt");a=a.indexOf("+")>=0?a:a+"+00:00";a=moment(a,g);this.set("createdAgo",a.fromNow())}},redirectPayload:function(){var a=h.redirectPayload.call(this);_.extend(a,{thread:this.id,zone:"internal_discovery"});return a},toJSON:function(){var a=h.toJSON.call(this);if(a.preview)a.preview=a.preview.toJSON();return a},toString:function(){return"organic link: "+
h.toString.call(this)}})}(h);l.Advertisement=function(e){var g=e.prototype;return e.extend({idAttribute:"body_id",defaults:_.defaults({brand:"",headline:"",text:"",url:"",advertisement_id:0,body_id:0,mobile:!0},g.defaults),get:function(a){if(a==="title")return this.attributes.headline;if(a==="link")return this.attributes.url;return g.get.call(this,a)},redirectPayload:function(){var a=g.redirectPayload.call(this);_.extend(a,{zone:"promoted_discovery",advertisement_id:this.get("advertisement_id"),body_id:this.get("body_id")});
return a},toJSON:function(){var a=g.toJSON.call(this);a.title=a.headline;a.link=a.url;return a},toString:function(){return"promoted link: "+g.toString.call(this)}})}(h);if(DISQUS.testing)l.BaseContentModel=h;return l});
DISQUS.define("discovery",function(){var l={},g=DISQUS.use("discovery.collections"),h=DISQUS.use("discovery.views"),e=DISQUS.use("discovery.helpers");l.init=function(a){var b=_.object(_.map(["lineTruncationEnabled","consoleLoggingEnabled"],function(d){return d in a?[d,a[d]]:[d,k.prototype.defaults[d]]}));e.config(b);return new k(a)};var k=l.DiscoveryApp=Backbone.Model.extend({defaults:{name:"default",inlineMeta:!1,contentPreviews:!0,promotedEnabled:!1,topPlacementEnabled:!1,isExperiment:!1,redirectUrl:"//redirect.disqus.com/url",
listRelatedLimit:null,listPromotedLimit:null,httpTimeout:1E4,sourceThread:null,sourceForum:null,help:!1,display:!1,columnEveningEnabled:!0,numColumns:2,minPerColumn:1,maxPerColumn:2,toleranceCoefficient:1.2,minWidthForColumnLayout:440,containerId:"discovery",topPlacementContainerId:"discovery-top",innerContainerName:"discovery-main",sectionNames:["col-organic","col-promoted"],collectionTagName:"ul",collectionClassName:"discovery-posts",consoleLoggingEnabled:DISQUS.debug,lineTruncationEnabled:!0,session:null,
js:null,css:null},initialize:function(){var a=this;a.createDataReferences();a.set("innerContainerId",a.get("innerContainerName")+"-"+a.cid);a.set("sectionIds",_.map(a.get("sectionNames"),function(d){return d+"-"+a.cid}));var b=a.get("session");a.get("topPlacementEnabled")&&b.isAnonymous()&&a.set("containerId",a.get("topPlacementContainerId"));a.on("change:display",function i(){a.off("change:display",i);a.onComplete()});_.bindAll(a,"getContentPreviews","validateData","showData");a.run()},commonClickMetadata:function(){var a=
this.get("sourceThread"),b=this.get("sourceForum"),a={redirectUrl:this.get("redirectUrl"),sourceThreadId:a.id,forumId:b.pk,forum:b.id,majorVersion:this.majorVersion(),variant:this.get("name"),isExperiment:this.get("isExperiment")};if((b=this.get("session"))&&b.isRegistered())a.userId=b.user.id;return a},createDataReferences:function(){function a(){return{sourceThread:b.get("sourceThread"),modelAttributes:b.commonClickMetadata()}}var b=this;b.collections=[];var d=a();d.modelAttributes.createdAgo=!0;
this.threads=new g.RelatedThreadCollection(null,d);this.collections.push(this.threads);if(this.get("promotedEnabled"))this.ads=new g.AdvertisementCollection(null,a()),this.collections.push(this.ads)},run:function(){var a=_.bind(this.onComplete,this);this.getData().then(this.validateData).then(this.showData).otherwise(a)},getData:function(){function a(){return{timeout:b.get("httpTimeout"),data:{limit:d/b.collections.length*b.get("maxPerColumn")}}}var b=this,d=b.get("numColumns"),i=a();if(b.has("listRelatedLimit"))i.data.limit=
b.get("listRelatedLimit");var e=b.listRelatedRequest=when(b.threads.fetch(i));b.get("contentPreviews")&&(e=e.then(b.getContentPreviews));if(!b.get("promotedEnabled"))return e;i=a();b.has("listPromotedLimit")?i.data.limit=b.get("listPromotedLimit"):i.data.limit*=2;i=b.listPromotedRequest=when(b.ads.fetch(i));return when.join(e,i)},getContentPreviews:function(){var a=this.threads.filter(function(a){return!a.get("posts")});DISQUS.debug||_.each(a,function(a){e.log("Rejecting "+a);e.log("Reason: Thread at that link has no comments");
this.threads.remove(a)},this);var a=this.threads.pluck("id"),b=this.collections.length,d=this.get("numColumns"),i=this.get("minPerColumn");if(a.length<d/b*i)return when.resolve();this.previews=new g.PostCollection;return(this.listTopPostRequest=when(this.previews.fetch({data:{thread:a},timeout:this.get("httpTimeout")}))).then(_.bind(this.attachPreviews,this))},attachPreviews:function(){var a=this;a.previews.each(function(b){var d=b.get("thread");(d=a.threads.get(d.id||d))&&d.set("preview",b)})},validateCollections:function(){for(var a=
this.collections,b=a.length,d=this.get("numColumns"),i=this.get("minPerColumn"),e,f;b>0;)if(f=d/a.length*i,e=a[--b],e.length<f)a.splice(b,1),b=a.length;b=a.length;if(b>0){d=d/b*this.get("maxPerColumn");for(i=0;i<b;i++)e=a[i],e.length>d&&e.reset(e.slice(0,d))}},validateData:function(){e.isMobile()&&this.ads&&this.ads.length>0&&this.ads.remove(this.ads.where({mobile:!1}));this.validateCollections();if(this.collections.length===0)throw"Not enough data";},showData:function(){h.BaseView.variant=this.toJSON();
var a=document.getElementById(this.get("containerId"));if(!a)throw"No container on the DOM";a=this.mainView=new h.MainView({el:a,model:this});a.render();var b=this.get("sectionIds"),d=this.get("collectionTagName"),i=this.get("collectionClassName");this.views=_.map(this.collections,function(a,e){return new h.BaseCollectionView({collection:a,el:$("#"+b[e]+" "+d+"."+i)})});this.views.length===2&&a.$el.find("#"+this.get("innerContainerId")).addClass("doublesection");_.invoke(this.views,"render");if(this.get("columnEveningEnabled")&&
a.$el.width()>this.get("minWidthForColumnLayout"))(new h.TwoColumn({views:this.views,fudge:this.get("toleranceCoefficient")})).render();else{var e=_.min(_.pluck(this.collections,"length"));_.each(this.views,function(a){for(;a.collection.length>e;)a.collection.pop()})}this.set("display",!0)},onComplete:function(a){var b=e.log;if(this.onCompleteCalled)return b("Error: Final reporting function called more than once");this.onCompleteCalled=!0;a&&b("It looks like there was a problem:",a);this.report()},
report:function(){var a=e.log,b=this.snapshot(),d=DISQUS.juggler.client("juggler");if(!d)return void a("Cannot report app state, no client found");a("Sending analytics data about this Discovery impression:");a("init_discovery: ",b);d.emit("init_discovery",b);this.get("darkJester")&&DISQUS.juggler.client("jester",!0).emit("init_discovery",b)},majorVersion:function(){return this.get("promotedEnabled")?"midway":"metadata"},snapshot:function(){var a=this.collections,b=this.threads,b={major_version:this.majorVersion(),
internal_organic:b.length,external_organic:0,promoted:0,display:this.get("display"),placement:this.get("containerId")===this.get("topPlacementContainerId")?"top":"bottom"};if(this.get("promotedEnabled")){var d=this.ads;_.extend(b,{promoted:d.length,promoted_ids:DISQUS.JSON.stringify(d.pluck("advertisement_id"))})}a=_.extend.apply(_,[{}].concat(_.pluck(a,"bandit")));if(!_.isEmpty(a))b.bandit=DISQUS.JSON.stringify(a);if(this.get("isExperiment"))b.variant=this.get("name");return b}});return l});
DISQUS.define("discovery.views",function(){var l={},g=DISQUS.use("discovery.helpers"),h=l.BaseView=Backbone.View.extend({template:function(a,b){if(h.variant)a.variant=h.variant;b=b||this.templateName;return DISQUS.renderBlock(b,a)}});l.BaseCollectionView=h.extend({events:{"click [data-redirect]":"handleClick"},handleClick:function(a){this.swapHref(a.currentTarget)},swapHref:function(a){a.setAttribute("data-href",a.getAttribute("href"));a.setAttribute("href",a.getAttribute("data-redirect"));_.delay(function(){a.setAttribute("href",
a.getAttribute("data-href"))},100)},templateName:"discoveryCollection",initialize:function(){this.elementsSelector="li.discovery-post";this.$elements=this.$el.find(this.elementsSelector);this.collectionName="collection";var a=this.collection;a.on("remove",this.remove,this);a.on("reset",this.render,this)},truncate:function(){this.$el.find(".line-truncate").each(function(a){a=$(a);g.lineTruncate(a,{lines:a.attr("data-line-truncate"),ellipsis:!0})})},render:function(){var a={};a[this.collectionName]=
this.collection.toJSON();this.$el.html(this.template(a));this.$elements=this.$el.find(this.elementsSelector);this.truncate();return this},remove:function(a,b,e){if(arguments.length===0)return h.prototype.remove.call(this);var f=_.toArray(this.$elements),g=f.splice(e.index,1)[0];$(g).remove();this.$elements=$(f);return this}});var e=function(a,b){this.modelIds=a||[];this.$elements=$(b||[])};_.extend(e.prototype,{height:function(){var a=this;a.heights=[];var b=$(a.$elements),e=b.first().offset().top,
e=function(){var a=b.last().offset();return a.top+a.height}()-e,f=0;_.each(b,function(b){b=$(b).height();a.heights.push(b);f+=b});this.interstice=(e-f)/(b.length-1);return e}});var k=function(){this.divideIntoColumns=function(){var a=this,b=a.subviews[0];a.left=new e;a.right=new e;var g=0;b.collection.each(function(e,m){var h=g++%2===0?"left":"right";a[h].modelIds.push(e.id);Array.prototype.push.call(a[h].$elements,b.$elements[m])})};this.removeOneFromColumn=function(a,b){var e=_.chain(a.modelIds).map(function(b,
e){return[b,a.heights[e]]}).sortBy(function(a){return-1*a[1]}).find(function(a){return a[1]<=b}).value()[0],f=this.subviews[0].collection,g=f.models,h=f.get(e),l=g.indexOf(h),e=[[],[]],k,n=g.length;for(k=0;k<n;k++)e[k%2].push(g[k]);g=e[l%2];g.splice(_.indexOf(g,h),1);g=[];h=(l+1)%2;for(k=0;k<n-1;k++)g.push(e[(k+h)%2].shift());f.reset(g)};this.balanceColumns=function(){var a=this.subviews[0],b=a.collection,e={};b.each(function(b,f){e[f]=a.$elements[f]});var f=g.balancedPartition(e),f=_.sortBy(f,"length"),
h=f[0],k=b.models,l=Array(k.length);_.each(f[1],function(a,b){l[2*b]=k[b]});_.each(h,function(a,b){l[2*b+1]=k[b]});b.reset(k)};this.shortenColumn=function(a,b){this.subviews[0].collection.length%2!==0&&a===this.left?this.removeOneFromColumn(a,this.fudge*b):this.balanceColumns()}},a=function(){this.divideIntoColumns=function(){var a=this.subviews,b=a[0],a=a[1];this.left=new e(b.collection.pluck(b.collection.model.prototype.idAttribute),b.$elements);this.right=new e(a.collection.pluck(a.collection.model.prototype.idAttribute),
a.$elements)};this.shortenColumn=function(a,b){for(var e=a===this.left?this.right:this.left,f=b/e.$elements.length,g=(a===this.left?this.subviews[0]:this.subviews[1]).collection,h=_.chain(a.modelIds).map(function(b,e){return[b,a.heights[e]]}).sortBy(function(a){return a[1]}).value(),k=[],l=0,n=b,n=f;h.length;){var u=h.pop(),r=u[0],u=u[1]+a.interstice;l+u>b&&(e=a);n=Math.abs(b-(l+u));n/=e.$elements.length;n>=f||(f=n,n=a.modelIds.indexOf(r),a.modelIds.splice(n,1),Array.prototype.splice.call(a.$elements,
n,1),l+=u,k.push(r))}g.remove(k)}},b=l.TwoColumn=function(b){this.fudge=b.fudge;this.subviews=b.views.slice(0,2);this.subviews.length===1?k.call(this):a.call(this)};_.extend(b.prototype,{ascendingByHeight:function(){var a=this.left,b=this.right,a=[[a,a.height()],[b,b.height()]];return _.sortBy(a,function(a){return a[1]})},evenColumns:function(a){var b=this.ascendingByHeight(),e=b[0][0],f=b[0][1],g=b[1][0],b=b[1][1];if(f!==b){var f=b-f,h=this.fudge*f,b=_.find(g.heights,function(a){return a+g.interstice<
h});if(!a&&b)return this.shortenColumn(g,f),this.divideIntoColumns(),this.evenColumns("do not recurse again");this.increaseMargins(e,f)}},increaseMargins:function(a,b){var e=b/a.$elements.length;_.each(a.$elements,function(a){var a=$(a),b=parseInt(a.css("margin-bottom"),10)+e;a.css("margin-bottom",b+"px")});(a===this.left?this.right:this.left).$elements.css("clear",a===this.right?"left":"right")},render:function(){this.divideIntoColumns();this.evenColumns();return this}});l.MainView=h.extend({templateName:"discoveryMain",
events:{"click [data-action=discovery-help]":function(a){a.preventDefault();this.model.set("help",!0)},"click [data-action=discovery-help-close]":function(a){a.preventDefault();this.model.set("help",!1)}},toggleHelp:function(a){this.$el.find("#discovery-note").toggle();a.trigger("resize")},initialize:function(){this.model.on("change:display",this.show,this);this.model.on("change:help",this.toggleHelp,this);this.$el.css({position:"absolute",visibility:"hidden",display:"block"})},createSections:function(){var a=
this.model,b=DISQUS.discovery.collections,e=b.RelatedThreadCollection,f=b.AdvertisementCollection,g=a.get("sectionNames"),h=a.get("sectionIds");return _.map(a.collections,function(a,b){var d;a instanceof e?d="organic":a instanceof f&&(d="promoted");return{id:h[b],className:g[b],type:d}})},render:function(){var a=this.model,b=this.createSections();this.$el.html(this.template({id:a.get("innerContainerId"),sections:b,forum:a.get("sourceForum"),session:a.get("session").toJSON()}))},show:function(a){a.get("display")&&
(this.$el.css({position:"static",visibility:"visible"}),a.trigger("resize"))}});return l});