var DISQUS=function(h){var d=h.DISQUS||{};d.AssertionError=function(a){this.message=a};d.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};d.assert=function(a,b,e){if(!a)if(e)h.console&&h.console.log("DISQUS assertion failed: "+b);else throw new d.AssertionError(b);};var b=[];d.define=function(a,f){typeof a==="function"&&(f=a,a="");for(var e=a.split("."),g=e.shift(),c=d,o=(f||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},h);g;)c=c[g]?c[g]:c[g]={},g=e.shift();for(var i in o)o.hasOwnProperty(i)&&(!o.__overwrites__&&c[i]!==null&&d.assert(!c.hasOwnProperty(i),"Unsafe attempt to redefine existing module: "+i,!0),c[i]=o[i],b.push(function(a,g){return function(){delete a[g]}}(c,i)));return c};d.use=function(a){return d.define(a)};d.cleanup=function(){for(var a=0;a<b.length;a++)b[a]()};return d}(window);
DISQUS.define(function(h,d){var b=h.DISQUS,a=h.document,f=a.getElementsByTagName("head")[0]||a.body,e={running:!1,timer:null,queue:[]};b.defer=function(a,c){function b(){var a=e.queue;if(a.length===0)e.running=!1,clearInterval(e.timer);for(var g=0,c;c=a[g];g++)c[0]()&&(a.splice(g--,1),c[1]())}e.queue.push([a,c]);b();if(!e.running)e.running=!0,e.timer=setInterval(b,100)};b.each=function(a,c){var b=a.length,f=Array.prototype.forEach;if(isNaN(b))for(var e in a)a.hasOwnProperty(e)&&c(a[e],e,a);else if(f)f.call(a,
c);else for(f=0;f<b;f++)c(a[f],f,a)};b.extend=function(a){b.each(Array.prototype.slice.call(arguments,1),function(c){for(var b in c)a[b]=c[b]});return a};b.serializeArgs=function(a){var c=[];b.each(a,function(a,b){a!==d&&c.push(b+(a!==null?"="+encodeURIComponent(a):""))});return c.join("&")};b.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};b.serialize=function(a,c,f){c&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=b.serializeArgs(c));if(f)return c=
{},c[(new Date).getTime()]=null,b.serialize(a,c);c=a.length;return a.charAt(c-1)=="&"?a.slice(0,c-1):a};b.require=function(g,c,e,d,l){function h(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))d&&d(),q&&clearTimeout(q),b.bean.remove(a.target,p,h)}var k=a.createElement("script"),p=k.addEventListener?"load":"readystatechange",q=null;k.src=b.serialize(g,c,e);k.async=!0;k.charset="UTF-8";(d||l)&&b.bean.add(k,p,h);l&&(q=setTimeout(function(){l()},2E4));f.appendChild(k);return b};
b.requireStylesheet=function(g,c,e){var d=a.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=b.serialize(g,c,e);f.appendChild(d);return b};b.requireSet=function(a,c,f){var e=a.length;b.each(a,function(a){b.require(a,{},c,function(){--e===0&&f()})})};b.injectCss=function(b){var c=a.createElement("style");c.setAttribute("type","text/css");b=b.replace(/\}/g,"}\n");h.location.href.match(/^https/)&&(b=b.replace(/http:\/\//g,"https://"));c.styleSheet?c.styleSheet.cssText=b:c.appendChild(a.createTextNode(b));
f.appendChild(c)}});
DISQUS.define("JSON",function(){function h(a){return a<10?"0"+a:a}function d(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var c=i[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(a,e){var g,h,i,m,k=c,n,j=e[a];j&&typeof j==="object"&&typeof j.toJSON==="function"&&!f&&(j=j.toJSON(a));typeof l==="function"&&(j=l.call(e,a,j));switch(typeof j){case "string":return d(j);case "number":return isFinite(j)?String(j):"null";case "boolean":case "null":return String(j);
case "object":if(!j)return"null";c+=o;n=[];if(Object.prototype.toString.apply(j)==="[object Array]"){m=j.length;for(g=0;g<m;g+=1)n[g]=b(g,j)||"null";i=n.length===0?"[]":c?"[\n"+c+n.join(",\n"+c)+"\n"+k+"]":"["+n.join(",")+"]";c=k;return i}if(l&&typeof l==="object"){m=l.length;for(g=0;g<m;g+=1)h=l[g],typeof h==="string"&&(i=b(h,j))&&n.push(d(h)+(c?": ":":")+i)}else for(h in j)Object.hasOwnProperty.call(j,h)&&(i=b(h,j))&&n.push(d(h)+(c?": ":":")+i);i=n.length===0?"{}":c?"{\n"+c+n.join(",\n"+c)+"\n"+
k+"}":"{"+n.join(",")+"}";c=k;return i}}var a={},f=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+h(this.getUTCMonth()+1)+"-"+h(this.getUTCDate())+"T"+h(this.getUTCHours())+":"+h(this.getUTCMinutes())+":"+h(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,o,i={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;a.stringify=function(a,f,g){var e;o=c="";if(typeof g==="number")for(e=0;e<g;e+=1)o+=" ";else typeof g==="string"&&(o=g);if((l=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return b("",{"":a})};a.parse=function(a,c){function b(a,
f){var g,e,d=a[f];if(d&&typeof d==="object")for(g in d)Object.hasOwnProperty.call(d,g)&&(e=b(d,g),e!==void 0?d[g]=e:delete d[g]);return c.call(a,f,d)}var f,a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),
typeof c==="function"?b({"":f},""):f;throw new SyntaxError("JSON.parse");};var m={a:[1,2,3]},k,p;if(Object.toJSON&&Object.toJSON(m).replace(/\s/g,"")==='{"a":[1,2,3]}')k=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(m='{"a":[1,2,3]}'.evalJSON(),m.a&&m.a.length===3&&m.a[2]===3&&(p=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),f=!(a&&a.length===3&&a[2]===3))})();if(f||!k||!p)return{stringify:a.stringify,parse:a.parse};return{stringify:k,
parse:p}});
DISQUS.define("Bus",function(){function h(a){a=a.split("/");return a[0]+"//"+a[2]}var d=DISQUS.use("JSON"),b=window.location.hash.slice(1),a=window.opener||window.parent,f=document.referrer,e={};e.client=h(document.location.href);e.host=f?h(f):e.client;return{origins:e,messageHandler:function(a){var c;try{c=DISQUS.JSON.parse(a.data)}catch(b){return}if(!c.name||!(c.name[0]==="!"&&a.origin!==e.client))switch(c.scope){case "client":DISQUS.Bus.trigger(c.name,c.data)}},postMessage:function(f){f.sender=b;
f=d.stringify(f);a.postMessage(f,"*")},sendHostMessage:function(a,c){c=c||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:c})},sendGlobalMessage:function(a,c){c=c||[];DISQUS.Bus.postMessage({scope:"global",name:a,data:c})}}});_.extend(DISQUS.Bus,Backbone.Events);
$(document).ready(function(){var h=window.addEventListener?window.addEventListener:window.attachEvent,d=window.addEventListener?"message":"onmessage";if(!h)throw Error("No event support.");h(d,DISQUS.Bus.messageHandler,!1);window.onunload=function(){DISQUS.Bus.sendHostMessage("die")}});
DISQUS.define(function(h,d){var b={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:require("bean"),debug:!1,browser:{mobile:/iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)},modules:{},strings:{translations:{}}};b.strings.get=_.bind(function(a){var b=this.translations[a];return b!==d?b:a},b.strings);b.interpolate=function(a,b){return a.replace(/%\(\w+\)s/g,
function(e){var e=e.slice(2,-2),g="";e in b?g=b[e]!==d&&b[e]!==null?b[e].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+e+"` not found in context for: ",a);return g})};h.gettext=_.bind(b.strings.get,b.strings);b.templateGlobals={urls:DISQUS.use("urls"),sso:null,gettext:b.strings.get};b.renderBlock=function(a,f){return Handlebars.partials[a](f||{},{data:b.templateGlobals})};b.assureOffset=function(a){return a.indexOf("+")>=0?a:a+"+00:00"};return b});
DISQUS.define("urls",function(){var h=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",d=encodeURIComponent(document.referrer),b={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1367873877",translations:"http://mediacdn.disqus.com/1367873877/build/lang",loading:"http://mediacdn.disqus.com/1367873877/html/simple-loading.html",realertime:"",juggler:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+
d,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1367873877/img/next/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1367873877"+h};window.location.protocol===
"https:"&&(b=_.extend(b,{root:"",media:"",translations:"https://securecdn.disqus.com/1367873877/build/lang",loading:"/html/simple-loading.html",api:b.apiSecure,logout:"https://disqus.com/logout/?redirect="+d,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"/img/next/noavatar92.png"},linkAffiliatorClient:""+
h}));return b});
DISQUS.define("api",function(){function h(a){function b(d){var g=d.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,g.length)===g&&(d=DISQUS.JSON.parse(d.originalEvent.data),d.requestId===e&&(g=d.code===0?a.success:a.error,delete d.requestId,(g||function(){})(d),document.body.removeChild(i),document.body.removeChild(c),$(window).off("message",b)))}var e=_.uniqueId("ft_"),d=document.createElement("div"),c=document.createElement("form"),h="frame_"+e,i;d.innerHTML='<iframe name="'+h+'"></iframe>';
i=d.childNodes[0];c.target=h;c.action=a.url.replace(".json",".pm");c.method=a.method||"GET";a.data=_.extend(a.data,{callback:e,referrer:document.referrer});_.each(a.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var f=document.createElement("input");f.type="hidden";f.name=b;f.value=a;c.appendChild(f)})});$(window).on("message",b);document.body.appendChild(i);document.body.appendChild(c);c.submit()}function d(a){a=_.defaults(a,b);a.data=a.data||
{};a.data.api_key=DISQUS.apiKey;return $.ajax(a)}var b={};return{defaults:function(a){var f,d,g;for(f in a)d=a[f],g=b[f],_.isObject(d)&&_.isObject(g)?_.extend(g,d):b[f]=d},headers:function(a){a=_.extend({},b.headers,a);b.headers=_.pick(a,_.map(a,function(a,b){if(a)return b}));return b.headers},getURL:function(a,b){b=b||{};if(b.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+a;return DISQUS.urls.api+a},ajax:d,call:function(a,b){b=b||{};b.url=DISQUS.api.getURL(a,{secure:b.secure});
b.data=_.extend(b.data||{},{api_key:DISQUS.apiKey});return(b.secure?h:d)(b)}}});(function(h){var d=DISQUS.Bus,b=DISQUS.api.getURL("internal/switches/list.jsonp");h.switches_jsonp_cb=function(a){d.sendHostMessage("switches.received",a.response)};d.on("fetch",function(a){a=a||{};a.data=a.data||{};a.data.callback="switches_jsonp_cb";a.data.api_key=DISQUS.apiKey;a=DISQUS.serialize(b,a.data,!1);DISQUS.require(a)});d.sendHostMessage("ready")})(this);